apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::978855859471:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::978855859471:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1OJFAEKM3MP5O
      username: system:node:{{EC2PrivateDNSName}}  
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-08T00:05:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1303"
  uid: d09b921e-3d53-4cc2-b4c1-b649072b9b84
